services:
  - type: web
    name: beautygo-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: BOT_TOKEN
        value: 8672113677:AAGmhmTyAn9TRgdB_e5BsPJKL_qe0CwiGrM
      - key: NETLIFY_URL
        value: https://symphonious-narwhal-e76970.netlify.app
      - key: NODE_ENV
        value: production
